#!/bin/bash

docker stop centaurid
docker rm centaurid

if [[ "$1" == "stop" ]]; then
    exit 0
fi

docker volume create centaurid-data || true
docker run --name centaurid \
    --platform linux/arm/v7 \
    -p 5664:5664/tcp \
    -p 5665:5665/tcp \
    -p 5665:5665/udp \
    -p 5666:5666/tcp \
    --net centauri \
    --env CENTAURI_CONFIG=/config/centauri.yaml \
    -v centaurid-data:/data \
    -v $PWD/centauri.yaml:/config/centauri.yaml \
    -d registry.lestak.sh/centaurid:22811c592ac0e25b9ee00b8c22520884ffbbbb35